//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AVRProjectIDE {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class filetemplates {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal filetemplates() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AVRProjectIDE.filetemplates", typeof(filetemplates).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*
        /// * 
        /// * Copyright somename %DATETIME:yyyy%
        /// *
        /// *
        /// */
        ///.
        /// </summary>
        internal static string copyright {
            get {
                return ResourceManager.GetString("copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // %FILENAME% created for project %PROJNAME% on %DATETIME:MM/dd/yyyy hh:mm:ss%
        ///
        ///%INCTEMPLATEFILE:copyright.txt%
        ///
        ///.
        /// </summary>
        internal static string defaultcode {
            get {
                return ResourceManager.GetString("defaultcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // %FILENAME% created for project %PROJNAME% on %DATETIME:MM/dd/yyyy hh:mm:ss%
        ///
        ///%INCTEMPLATEFILE:copyright.txt%
        ///
        ///#ifndef %FILENAMENOEXT%_%FILEEXT%
        ///#define %FILENAMENOEXT%_%FILEEXT%
        ///
        ///
        ///
        ///#endif.
        /// </summary>
        internal static string defaultheader {
            get {
                return ResourceManager.GetString("defaultheader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // %FILENAME% created for project %PROJNAME% on %DATETIME:MM/dd/yyyy hh:mm:ss%
        ///
        ///%INCTEMPLATEFILE:copyright.txt%
        ///
        ///int main()
        ///{
        ///
        ///	return 0;
        ///}.
        /// </summary>
        internal static string initialmain {
            get {
                return ResourceManager.GetString("initialmain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // %FILENAME% created for project %PROJNAME% on %DATETIME:MM/dd/yyyy hh:mm:ss%
        ///
        ///%INCTEMPLATEFILE:copyright.txt%
        ///
        ///void setup()
        ///{
        ///
        ///}
        ///
        ///void loop()
        ///{
        ///
        ///}.
        /// </summary>
        internal static string initialpde {
            get {
                return ResourceManager.GetString("initialpde", resourceCulture);
            }
        }
    }
}
