//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AVRProjectIDE.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AVRProjectIDE.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to int main(void)
        ///{
        ///	init();
        ///
        ///	setup();
        ///    
        ///	for (;;)
        ///		loop();
        ///        
        ///	return 0;
        ///}
        ///
        ///.
        /// </summary>
        internal static string arduinomain {
            get {
                return ResourceManager.GetString("arduinomain", resourceCulture);
            }
        }
        
        internal static byte[] arduinomakefile {
            get {
                object obj = ResourceManager.GetObject("arduinomakefile", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;AutoComplete&gt;
        ///  &lt;C&gt;
        ///    &lt;Group type=&quot;statements&quot;&gt;
        ///      if else do while for switch case default break goto continue return sizeof main
        ///    &lt;/Group&gt;
        ///    &lt;Group type=&quot;types&quot;&gt;
        ///      void bool boolean byte char short int long word dword float double bool bit bitfield byte uchar ushort uint ulong uword struct union enum
        ///    &lt;/Group&gt;
        ///    &lt;Group type=&quot;modifiers&quot;&gt;
        ///      signed unsigned static volatile const inline extern typedef
        ///    &lt;/Group&gt;
        ///    &lt;Group type=&quot;pre [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string autocomplete {
            get {
                return ResourceManager.GetString("autocomplete", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap build {
            get {
                object obj = ResourceManager.GetObject("build", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AVRProjectIDE_Alpha55.
        /// </summary>
        internal static string BuildID {
            get {
                return ResourceManager.GetString("BuildID", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap burn {
            get {
                object obj = ResourceManager.GetObject("burn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap comment {
            get {
                object obj = ResourceManager.GetObject("comment", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap configure {
            get {
                object obj = ResourceManager.GetObject("configure", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap copy {
            get {
                object obj = ResourceManager.GetObject("copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cut {
            get {
                object obj = ResourceManager.GetObject("cut", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap exit {
            get {
                object obj = ResourceManager.GetObject("exit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap file {
            get {
                object obj = ResourceManager.GetObject("file", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap find {
            get {
                object obj = ResourceManager.GetObject("find", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap findnext {
            get {
                object obj = ResourceManager.GetObject("findnext", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap header {
            get {
                object obj = ResourceManager.GetObject("header", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap help {
            get {
                object obj = ResourceManager.GetObject("help", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;HelpLinks&gt;
        ///  &lt;Link Text=&quot;AVR-Libc Reference&quot; URL=&quot;http://www.nongnu.org/avr-libc/user-manual/&quot;&gt;
        ///    &lt;Link Text=&quot;Library Reference&quot; URL=&quot;http://www.nongnu.org/avr-libc/user-manual/modules.html&quot; /&gt;
        ///    &lt;Link Text=&quot;Interrupts&quot; URL=&quot;http://www.nongnu.org/avr-libc/user-manual/group__avr__interrupts.html&quot; /&gt;
        ///    &lt;Link Text=&quot;FAQ&quot; URL=&quot;http://www.nongnu.org/avr-libc/user-manual/FAQ.html&quot; /&gt;
        ///  &lt;/Link&gt;
        ///  &lt;Link Text=&quot;Baud Rate Chart&quot; URL=&quot;http://www.wormfood.net/avrbaudc [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string helplinks {
            get {
                return ResourceManager.GetString("helplinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://code.google.com/p/avr-project-ide/wiki/Help.
        /// </summary>
        internal static string HelpURL {
            get {
                return ResourceManager.GetString("HelpURL", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap hppheader {
            get {
                object obj = ResourceManager.GetObject("hppheader", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap indent {
            get {
                object obj = ResourceManager.GetObject("indent", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;us-ascii&quot;?&gt;
        ///&lt;InterruptVectors&gt;
        ///	&lt;ListOfVectors&gt;
        ///		&lt;Vector Text=&quot;ADC Conversion Complete&quot;&gt;
        ///			&lt;NewName&gt;ADC_vect&lt;/NewName&gt;
        ///			&lt;OldName&gt;SIG_ADC&lt;/OldName&gt;
        ///			&lt;Desc&gt;ADC Conversion Complete&lt;/Desc&gt;
        ///		&lt;/Vector&gt;
        ///		&lt;Vector Text=&quot;Analog Comparator 0&quot;&gt;
        ///			&lt;NewName&gt;ANALOG_COMP_0_vect&lt;/NewName&gt;
        ///			&lt;OldName&gt;SIG_COMPARATOR0&lt;/OldName&gt;
        ///			&lt;Desc&gt;Analog Comparator 0&lt;/Desc&gt;
        ///		&lt;/Vector&gt;
        ///		&lt;Vector Text=&quot;Analog Comparator 1&quot;&gt;
        ///			&lt;NewName&gt;ANALOG_COMP_1_vect&lt;/NewName&gt;
        ///			&lt;OldName&gt;SIG_COMP [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string interruptvectors {
            get {
                return ResourceManager.GetString("interruptvectors", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap missing {
            get {
                object obj = ResourceManager.GetObject("missing", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap newFile {
            get {
                object obj = ResourceManager.GetObject("newFile", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap nocompile {
            get {
                object obj = ResourceManager.GetObject("nocompile", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap paste {
            get {
                object obj = ResourceManager.GetObject("paste", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap redo {
            get {
                object obj = ResourceManager.GetObject("redo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap redo1 {
            get {
                object obj = ResourceManager.GetObject("redo1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap save {
            get {
                object obj = ResourceManager.GetObject("save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap saveall {
            get {
                object obj = ResourceManager.GetObject("saveall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Styles&gt;
        ///  &lt;Style Name=&quot;ASM&quot;						/&gt;
        ///  &lt;Style Name=&quot;ATTRIBUTE&quot;					ForeColor=&quot;Red&quot; /&gt;
        ///  &lt;Style Name=&quot;BACKTICKS&quot;					ForeColor=&quot;Red&quot; /&gt;
        ///  &lt;Style Name=&quot;BINARY&quot;					ForeColor=&quot;Orange&quot; /&gt;
        ///  &lt;Style Name=&quot;BINNUMBER&quot;					ForeColor=&quot;Orange&quot; /&gt;
        ///  &lt;Style Name=&quot;BRACELIGHT&quot;				ForeColor=&quot;Red&quot; Bold=&quot;True&quot;/&gt;
        ///  &lt;Style Name=&quot;BLOCK_COMMENT&quot;				ForeColor=&quot;Green&quot; /&gt;
        ///  &lt;Style Name=&quot;CHAR&quot;						ForeColor=&quot;Red&quot; /&gt;
        ///  &lt;Style Name=&quot;CHARACTER&quot;					ForeColor=&quot;Red&quot; /&gt;
        ///  &lt;Style Name=&quot;CLA [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string scintconfig {
            get {
                return ResourceManager.GetString("scintconfig", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap search {
            get {
                object obj = ResourceManager.GetObject("search", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap searchall {
            get {
                object obj = ResourceManager.GetObject("searchall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon searchIco {
            get {
                object obj = ResourceManager.GetObject("searchIco", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap serial {
            get {
                object obj = ResourceManager.GetObject("serial", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon serialIco {
            get {
                object obj = ResourceManager.GetObject("serialIco", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SHELL32_223 {
            get {
                object obj = ResourceManager.GetObject("SHELL32_223", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;ProjTemplates&gt;
        ///
        ///  &lt;template name=&quot;Blank Template&quot;&gt;
        ///
        ///  &lt;/template&gt;
        ///
        ///  &lt;template name=&quot;Pin Definitions and Macros&quot;&gt;
        ///    &lt;CreateFile name=&quot;pindefs.h&quot;&gt;
        ///      &lt;Template&gt;defaultheader.txt&lt;/Template&gt;
        ///    &lt;/CreateFile&gt;
        ///    &lt;CreateFile name=&quot;macros.h&quot;&gt;
        ///      &lt;Template&gt;defaultheader.txt&lt;/Template&gt;
        ///    &lt;/CreateFile&gt;
        ///  &lt;/template&gt;
        ///
        ///  &lt;template name=&quot;Maximum Optimization&quot;&gt;
        ///    &lt;Optimization&gt;-Os&lt;/Optimization&gt;
        ///    &lt;PackStructs&gt;true&lt;/PackStructs&gt;
        ///    &lt;ShortEnums&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string templates {
            get {
                return ResourceManager.GetString("templates", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap treeroot {
            get {
                object obj = ResourceManager.GetObject("treeroot", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap uncomment {
            get {
                object obj = ResourceManager.GetObject("uncomment", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap undo {
            get {
                object obj = ResourceManager.GetObject("undo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap unindent {
            get {
                object obj = ResourceManager.GetObject("unindent", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap unknown {
            get {
                object obj = ResourceManager.GetObject("unknown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap unknown2 {
            get {
                object obj = ResourceManager.GetObject("unknown2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap warning {
            get {
                object obj = ResourceManager.GetObject("warning", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon warningIco {
            get {
                object obj = ResourceManager.GetObject("warningIco", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap web {
            get {
                object obj = ResourceManager.GetObject("web", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://code.google.com/p/avr-project-ide/.
        /// </summary>
        internal static string WebsiteURL {
            get {
                return ResourceManager.GetString("WebsiteURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://sourceforge.net/projects/winavr/files/.
        /// </summary>
        internal static string WinAVRURL {
            get {
                return ResourceManager.GetString("WinAVRURL", resourceCulture);
            }
        }
    }
}
